### ISSUE TITLE
`solid/reactivity` warning when using props as dependency(ies) in `on()`

### ISSUE THREAD

**Issue by gawlk** [solidjs-community/eslint-plugin-solid#105]
**Describe the bug**

ESLint shows a warning:

> This function should be passed to a tracked scope (like createEffect) or an event handler because it contains reactivity, or else changes will be ignored.eslint[solid/reactivity](https://github.com/solidjs-community/eslint-plugin-solid/blob/main/docs/reactivity.md)

When using a prop or several props as dependency(ies) in `on()` like so:

```ts
createEffect(
    on(
      () => props.show,
      (show) => show && setState('zIndex', 100),
    ),
  )
```

**To Reproduce**

The upper code

**Expected behavior**

To not show a warning when the code is right

**Screenshots**

<img width="505" alt="Screenshot 2023-08-21 at 11 38 47" src="https://github.com/solidjs-community/eslint-plugin-solid/assets/32246972/97b001e3-fa80-47a9-a635-e6922ac9b584">

**Environment (please complete the following information):**

- OS: Mac OS latest beta
- Node version (`node --version`): latest
- `eslint-plugin-solid` version (`npm list eslint-plugin-solid`/`yarn why eslint-plugin-solid`): latest
- `eslint` version (`npm list eslint`/`yarn why eslint`): latest

**Additional context**

- [ ] I would be willing to contribute a PR to fix this issue

**Comment by joshwilsonvu** [comment]
Looks like I can no longer reproduce this, must have fixed the issue. Feel free to reopen if I'm mistaken.

https://playground.solidjs.com/anonymous/c8858afd-2aa7-4366-9af0-977e650915ea
