### ISSUE TITLE
Types don't exist in bundled package

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [solidjs-community/eslint-plugin-solid#128]
**Describe the bug**

I'm trying to use `eslint-plugin-solid` in an `eslint.config.js` with TypeScript's `checkJs: true`. `eslint-plugin-solid`'s `package.json` claims `dist/index.d.ts` should exist:

https://github.com/solidjs-community/eslint-plugin-solid/blob/02d7879338bb0186f9765bb8dc537ba9f676e11f/package.json#L13

...but that file doesn't exist in the published package.

https://arethetypeswrong.github.io/?p=eslint-plugin-solid%400.13.1:

> [No types](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/UntypedResolution.md)

Import resolved to JavaScript files, but no type declarations were found.

**To Reproduce**

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAZwgG2AEzgMyhEcBEApgqgHYwC0YyArgObCkVKpr4DcAUJ4QB6Sw4aQpgCGNZPADaLdAF12QA

**Expected behavior**

Types should be included with the package.

**Environment (please complete the following information):**

- OS: [e.g. Mac OS 11, Windows 10] n/a
- Node version (`node --version`): n/a
- `eslint-plugin-solid` version (`npm list eslint-plugin-solid`/`yarn why eslint-plugin-solid`): 0.13.1
- `eslint` version (`npm list eslint`/`yarn why eslint`): n/a

**Additional context**

- [x] I would be willing to contribute a PR to fix this issue

**Comment by nix6839** [comment]
It seems like you are looking to use flat config, but the eslint-plugin-solid does not export flat config from the root of the module. Please refer to this link: https://github.com/solidjs-community/eslint-plugin-solid#flat-configuration

However, exporting the type is indeed a bug, so I will submit a PR for that.

Additionally, since other plugins supporting flat config export it from the root of the module, I will also submit a separate PR to export flat config from the root of the module for consistency.

**Comment by joshwilsonvu** [comment]
Thank you both—as you can probably expect, shipping types hasn't really been a priority until now, but it makes sense for use with flat config. I'll take a look at that PR

**Comment by pauliesnug** [comment]
I am also experiencing this issue, could this be merged? Thank you

**Comment by nix6839** [comment]
> Additionally, since other plugins supporting flat config export it from the root of the module, I will also submit a separate PR to export flat config from the root of the module for consistency.

I have opened a PR: https://github.com/solidjs-community/eslint-plugin-solid/pull/135
