### ISSUE TITLE
Support for eslint 9.0.0

### ISSUE THREAD

**Issue by AlbertSabate** [solidjs-community/eslint-plugin-solid#137]
**Describe the need**
ESLint 9.0.0 has been released as stable.

Currently, the ESlint version of this package is pointing to version 8.43.0, which has many deprecation notices for version 9.0.0.

This version updates the code to prevent using deprecated fn from version 8.x and start using the new fns of 9.x

The version has been updated to 8.56.0 and migrated to a non-deprecated FNS.

ESLint has not been bumped to version 9, as many changes are required to maintain backward compatibility. However, the package works well in the new version.

Tests are passing. And I tested a bit on my end. This is not a guarantee that I did not break anything. And Code reviews will be really appreciated :)

Note that the package has been bumped to 0.14.0.

**Suggested Solution**
Make it work

**Possible Alternatives**
NA

**Additional context**

- [ X] I would be willing to contribute a PR to implement this feature

https://github.com/solidjs-community/eslint-plugin-solid/pull/136

**Comment by AlbertSabate** [comment]
Hello @suiyun39, for you reference I've opened the PR https://github.com/solidjs-community/eslint-plugin-solid/pull/136 in regards of this issue, maybe you can continue from that branch if you want to amend anything? Will save you some hours of work :)

**Comment by suiyun39** [comment]
@AlbertSabate 

Thanks for reminding, that reference is only for tracking: when can upgrade my eslint config package to eslint 9.0.0.

At the same time, I'd be happy to make some contributions to this project. But at the moment, I don't know the guidelines for this update. For example, should new version be compatible with eslint 8.x? We should create a minor version or major version?

**Comment by AlbertSabate** [comment]
I would love to know it also. Maybe @joshwilsonvu can answer that? And let us know next steps?

In the meanwhile, for your reference, you can use the following with eslint 9.0.0 compatible using this in your package.json:

`"eslint-plugin-solid": "git://github.com/AlbertSabate/eslint-plugin-solid#06897bafb97bd31f4021bafb124badcf4589ba58",`

You can code review the changes on that commit.

**Comment by joshwilsonvu** [comment]
Hello, thank you all for taking the reins on this so far. (Started a new job recently and have been busy 🙂)

Currently, the plugin is tested with ESLint v8 down to v6. From what I understand, the breaking changes in ESLint v9 are fairly minor for plugin authors. I don't see a compelling reason to drop support for any old versions, until it becomes difficult to pass tests for those versions while supporting the newest version. 

Re: versioning, since we're still in v0.x, it technically doesn't matter too much, but adding support for v9 would count as a new feature and could go in a minor. I may take the opportunity to release a v1 major version bump (without breaking changes) once the current batch of PRs and issues are resolved. The pace of rapid changes has slowed enough for that to make sense to me, and I think big changes to `reactivity` can wait until a v2.

I intend to do as much of that as I can tomorrow, and make a few infra updates soon to make releases a less manual, time-intensive process. I'm very thankful for all the community involvement and would like to make this project more collaborative, so that I'm less of a bottleneck.

**Comment by pauliesnug** [comment]
v9 support was added to `eslint-plugin-solid` in https://github.com/solidjs-community/eslint-plugin-solid/pull/140, with https://github.com/solidjs-community/eslint-plugin-solid/pull/141 awaiting a peer dependency update

**Comment by Borber** [comment]
When can it be released?

**Comment by Crazytieguy** [comment]
It looks like the build failed due to the lint script failing:
```
> eslint --ext .js,.jsx,.ts,.tsx --ignore-pattern test/fixture/invalid . "--max-warnings=0"

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
 ELIFECYCLE  Command failed with exit code 2.
```

**Comment by pauliesnug** [comment]
@Crazytieguy @Borber It was just released in the latest 4 commits, including v9 and flat config support

**Comment by joshwilsonvu** [comment]
Yes--v9 support was released in v0.14.0! This v0.14.1 release just fixes the peer dependency and makes some internal updates to use ESLint v9, which don't affect users.

**Comment by onx2** [comment]
Is there an example implementation of this with v9 that I can look at?

**Comment by SomeAspy** [comment]
If you are looking for an example config, its for the most part quite simple.

You can see my config on my site [here](https://github.com/SomeAspy/aspy.dev/blob/main/eslint.config.js)
The [migration guide is also available](https://eslint.org/docs/latest/use/configure/migration-guide) on eslint's site 

However, the most basic configuration can be seen in the project readme, https://github.com/solidjs-community/eslint-plugin-solid?tab=readme-ov-file#flat-configuration

**Comment by onx2** [comment]
Whoops accidentally deleted my comment and meant to append.

I'm getting this error when running my lint:
`TypeError: solidEslintPlugin.configs.flat/typescript is not iterable`


```js
import pluginJs from "@eslint/js";
import solidEslintPlugin from "eslint-plugin-solid";
import globals from "globals";
import typescriptESLint from "typescript-eslint";

export default [
  {
    languageOptions: { globals: globals.browser },
  },
  {
    /**
     * @note Must be in its own object
     * @see  https://github.com/eslint/eslint/discussions/18304
     * @docs https://eslint.org/docs/latest/use/configure/configuration-files#configuration-objects
     */
    ignores: [
      "**/dist/*",
      "**/i18n/*",
      "**/*.d.ts",
      "**/*.generated.*",
      "**/storybook-static/*",
    ],
  },
  pluginJs.configs.recommended,
  ...typescriptESLint.configs.recommended,
  ...solidEslintPlugin.configs["flat/typescript"],
];
```

I got this format from https://github.com/solidjs-community/eslint-plugin-solid?tab=readme-ov-file#flat-configuration

**Comment by SomeAspy** [comment]
It looks like the issue here might be the spread operator in front of `solidEslintPlugin`

**Comment by onx2** [comment]
Oh boy... 🤦🏼 this is what I get for doing multiple things at once. Thank you.

**Comment by eagerestwolf** [comment]
So, this can be resolved once and for all now :tada:. `@typescript-eslint/utils` version 8 is out now with native support for ESLint 9. That was the only real issue I had noticed was `pnpm` complaining about that peer dep. Otherwise, it's been working fine for me. Granted, I don't quite follow the recommended config.

```js
// @ts-check

import { fixupConfigRules } from "@eslint/compat";
import js from "@eslint/js";
import gitignore from "eslint-config-flat-gitignore";
import jsxA111y from "eslint-plugin-jsx-a11y";
import perfectionist from "eslint-plugin-perfectionist";
import prettier from "eslint-plugin-prettier/recommended";
import solid from "eslint-plugin-solid/configs/typescript.js";
import tailwind from "eslint-plugin-tailwindcss";
import ts from "typescript-eslint";

/* @type {import("eslint").Linter.FlatConfig[]} */
export default [
  // Respect the .gitignore
  gitignore(),

  // JavaScript
  js.configs.recommended,

  // TypeScript
  ...ts.configs.recommendedTypeChecked,
  ...ts.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  // JavaScript...again
  {
    files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs"],
    ...ts.configs.disableTypeChecked,
  },

  // Pedanticism
  perfectionist.configs["recommended-natural"],

  // JSX/Solid/TailwindCSS
  ...fixupConfigRules(jsxA111y.flatConfigs.recommended),
  solid,
  ...tailwind.configs["flat/recommended"],

  // Prettier...because prettier
  prettier,

  // Rule overrides
  {
    rules: {
      "perfectionist/sort-imports": [
        "error",
        {
          groups: [
            ["builtin", "builtin-type"],
            ["external", "external-type"],
            ["internal", "internal-type"],
            ["parent", "parent-type"],
            ["sibling", "sibling-type"],
            ["index", "index-type"],
            ["side-effect", "side-effect-style"],
            ["object", "unknown"],
          ],
          ignoreCase: true,
          internalPattern: ["@/**"],
          newlinesBetween: "always",
          order: "asc",
          type: "natural",
        },
      ],
    },
  },
];

```

**Comment by pauliesnug** [comment]
This can be closed, the only thing missing is bumping our internal use of typescript-eslint@v8
