### ISSUE TITLE
Error upgrading from 0.14.2 to 0.14.3: ConfigError: Config (unnamed): Key "plugins": Cannot redefine plugin "solid".

### ISSUE THREAD

**Issue by amatiash** [solidjs-community/eslint-plugin-solid#157]
**Describe the bug**
Receive `ConfigError: Config (unnamed): Key "plugins": Cannot redefine plugin "solid".` error by running `eslint`

**To Reproduce**

esling.config.js
```javascript
import typescriptEslint from '@typescript-eslint/eslint-plugin'
import solid from 'eslint-plugin-solid'
import globals from 'globals'
import tsParser from '@typescript-eslint/parser'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import js from '@eslint/js'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: js.configs.recommended,
    allConfig: js.configs.all,
})

export default [...compat.extends(
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:solid/typescript',
    'paper',
), {
    plugins: {
        '@typescript-eslint': typescriptEslint,
        solid,
    },

    languageOptions: {
        globals: {
            ...globals.browser,
            ...Object.fromEntries(Object.entries(globals.node).map(([key]) => [key, 'off'])),
        },

        parser: tsParser,
        ecmaVersion: 2020,
        sourceType: 'module',
    }
}]

```

**Expected behavior**
No error

**Environment (please complete the following information):**

- OS: Mac OS 12.7.6 (21H1320)
- Node version (`node --version`): v20.9.0
- `eslint-plugin-solid` version (`npm list eslint-plugin-solid`/`yarn why eslint-plugin-solid`): eslint-plugin-solid@0.14.3
- `eslint` version (`npm list eslint`/`yarn why eslint`): eslint@9.9.1

**Comment by jcarpe** [comment]
FWIW - I can confirm this as well. Had the same experience.

- Node 22.1.0
- eslint-plugin-solid version 0.14.3
- eslint 9.9.1

When I drop back to eslint-plugin-solid version 0.14.3, no issue.

**Comment by amatiash** [comment]
> When I drop back to eslint-plugin-solid version 0.14.3, no issue.

@jcarpe Did you mean 0.14.2?

**Comment by jcarpe** [comment]
Apologies - updated the comment, but yes. When dropping back to **0.14.2**, no problem.

**Comment by joshwilsonvu** [comment]
I _think_ this might be an incompatibility with using `compat.extends`. Extending `'plugin:solid/typescript'` should already define the `solid` plugin, so you may need to remove it from your `plugins` object:

```diff
    plugins: {
        '@typescript-eslint': typescriptEslint,
-       solid,
    },

    languageOptions: {
```

Does this resolve your issue?

**Comment by amatiash** [comment]
> Does this resolve your issue?

It does! Thank you @joshwilsonvu !!!
