### ISSUE TITLE
rule links broken

### ISSUE THREAD

**Issue by hyperknot** [solidjs-community/eslint-plugin-solid#161]
Right on the main README, the rule links are broken, like:
https://github.com/solidjs-community/eslint-plugin-solid/blob/main/docs/components-return-once.md

Does this file exists somewhere?

**Comment by derekrjones** [comment]
the actual path to the docs are [`main`/packages/eslint-plugin-solid/docs/components-return-once.md](https://github.com/solidjs-community/eslint-plugin-solid/blob/main/packages/eslint-plugin-solid/docs/components-return-once.md)

same issue appears in my code editor with the problem links to documentation
