### ISSUE TITLE
Move eslint-plugin-soild to solidjs or solidjs-community

### ISSUE THREAD

**Issue by davedbase** [solidjs-community/eslint-plugin-solid#31]
I'm opening an issue to formalize a comment made on our DIscord (https://discord.com/channels/722131463138705510/722131463889223772/1017694782102966352). It would be interesting to bring this into SolidJS core or SolidJS Community.

Core is currently trying download a lot of the package responsibilities to community so there might not be a desire to make it core managed directly. If we do have an interest in making it core perhaps @modderme123 or @ryansolid would like to be directly involved.

If that's not the case I'm happy to bring it into solidjs-community which isn't directly core maintained but we do have oversight on it.

@joshwilsonvu of course your input as well here is necessary.

**Comment by joshwilsonvu** [comment]
Thanks for mentioning this @davedbase, I don't think it's a bad idea! It would just be a repository transfer, right?

I agree that this plugin might be a better fit for solidjs-community, because to date I haven't had much interaction with Solid core. That's fine, I don't think this project needs a tight integration with Solid's roadmap or anything.

You mention oversight—would anyone mind if I continued to commit to `main` instead of using branches/PRs, at least for smaller things? Anything else you mean by that?

Other than that it doesn't seem like it would be a big change for me, other than lending the repo a better sense of legitimacy from the new organization name. So I'm not opposed 👍🏼

**Comment by davedbase** [comment]
Yup, "oversight" simply means that we aren't directly responsible or involved however we do facilitate bringing contributors and ensuring critical pieces of ecosystem tooling are not abandoned or fall behind releases.

We absolutely want you in charge of the repo. You've done amazing work here and I want to ensure that you are encouraged and supported by core and the broader community to keep up the incredible work. This transfer is about bringing legitimacy to the work.

On that note I'd like to offer you a role on our Ecosystem Team. It's mostly a passive role that grants you access to our Ecosystem Discord chat. Core and Ecosystem maintain a close relationship and we tend share updates/ask for input with it as a priority. It's a way to stay close to the project and get recognition as a major ecosystem contributor.

**Comment by joshwilsonvu** [comment]
Perfect, that makes sense and helps me understand better why you'd want to make this move. I appreciate the flexibility—while I'd be happy to adopt a more formal process, the niche nature of this project means that I'm likely to keep working on it solo for the foreseeable future. 

I'd be honored to accept the Ecosystem Team role! I'm excited to have a more direct way to share my perspective as a tooling maintainer. I don't have a large amount of free time for Solid right now, but I'm looking forward to being able to tune in to a smaller chat when I can.

**Comment by davedbase** [comment]
I suspect you are correct that it is pretty niche, however some other ecosystem members do want to see this grow more as an effort. I expect you'll lead or be the primary on this effort but I also expect we may seem other interested parties participate which is a positive.

The Ecosystem chat isn't very fast-paced although sometimes becomes very lively. Let me know your Discord handle and I'll add the role to your profile. In the meantime, did you want to begin transferring to solidjs-community?

**Comment by joshwilsonvu** [comment]
Absolutely, I hope that's the case and definitely want to make this repo more open to group effort as the need arises.

I'm @joshwilsonvu on the Discord and elsewhere. I'll need permission to create repositories in solidjs-community, then I'll begin the transfer!
