### ISSUE TITLE
Add JSX style linting support?

### ISSUE THREAD

**Issue by jerryc05** [solidjs-community/eslint-plugin-solid#42]
**Describe the need**

Support JSX style formatting

**Suggested Solution**

Use `jsx-*` rules under https://github.com/jsx-eslint/eslint-plugin-react/tree/master/lib/rules

**Possible Alternatives**

**Additional context**

- [ ] I would be willing to contribute a PR to implement this feature

**Comment by joshwilsonvu** [comment]
Hello,

Thanks for the suggestion. I haven't tested this, but I believe that those JSX formatting rules from `eslint-plugin-react` will still work for Solid code if you configure them individually.

However, I recommend using [Prettier](https://prettier.io), an opinionated code formatter with great support for JSX. A lot of newer projects use both tools separately, with Prettier for formatting and ESLint for finding/fixing code problems. This helps keep your IDE from distracting you with warnings about formatting. The `eslint-config-prettier` package can help you disable all ESLint formatting rules. 

For that reason I'm not planning on adding support for other formatting concerns. (You could point to the `solid/self-closing-comp` rule as a counterexample, but that's not covered by auto formatters.)
